### ISSUE TITLE
bug - stop using -g flag for /bin/ls

### ISSUE THREAD

**Issue by afengler** [cschuber/freebsd-ftpd#2]
Currently ftpd will only show the group in a dir response, not the file owner. 

In https://reviews.freebsd.org/rG3bfbb521fef5764ecabc2bf3fdc76f47258171f8 the behaviour of ls was changed such that -g was no longer a noop for compatibility with BSD 4.3, but instead changed the output of long mode to exclude the owner of the file and display only the group.

There's a fix to the freebsd source to fix this, not sure if you want to pull from there or would rather me format a patch for here directly.

https://reviews.freebsd.org/D45291
https://cgit.freebsd.org/src/commit/?id=e20971500194d2f7299e9d01ca3b20e9bc6b4009

**Comment by cschuber** [comment]
Fixed by d716943.
